"""
Django settings for dondecomemos project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from django.utils.safestring import mark_safe
import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wg4w4f%e!9ao#79)l$2a$d5b*)1_#)4i-@gmc4*r(c$-ro%7*2'

# SECURITY WARNING: don't run with debug turned on in production!
try:
    from .local_settings import DEBUG_VALUE
    DEBUG = DEBUG_VALUE
except Exception as e:
    DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'guardian',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'fcm_django',
    'privacy.apps.PrivacyConfig',
    'superadmin.apps.SuperadminConfig',
    'restaurants.apps.RestaurantsConfig',
    'material.admin',
    'material.admin.default',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAA3yJhIq8:APA91bGJdfk3zvkmcwXBaA4vemXHzbzSwIReMzR660VuVbNLdRVqPmCO9-YY-YELl6kCryY0lfiJH5k4nOuURTR8ji5vkDCl-mg2hs_-jCJedLtxK4qABkO41vDWAGZ9seann5TETriz"
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'dondecomemos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dondecomemos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
try:
    from .local_settings import DB
    DATABASES = DB
except Exception as e:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config()
        }
    except Exception as ex:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'dondecomemos',#os.path.join(BASE_DIR, 'db.mysql'),
                'USER': 'root',
                'PASSWORD': 'hYguOjKg4UiX91c1gX6SAMJgHjTsASuO',
                'HOST': 'mysql',   # Or an IP Address that your DB is hosted on
                #'PORT': '3306'
            }
        }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MEDIA_ROOT = 'uploads'
MEDIA_URL = '/uploads/'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_L10N = True

USE_TZ = True


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = "/static/"

MATERIAL_ADMIN_SITE = {
    'HEADER':   mark_safe('<img height="35" style="margin-left: -30px;" width="40" src="{STATIC_URL}admin/img/icon.png"> donde comemos | Panel de Administración'.format(STATIC_URL=STATIC_URL)),
    'TITLE':  "donde comemos",
    'FAVICON':  "admin/img/icon.png",
    'MAIN_BG_COLOR':  "#333333",
    # 'MAIN_HOVER_COLOR':  "#fd9500",
    'MAIN_HOVER_COLOR':  "#ff7800",
    'PROFILE_PICTURE':  "admin/img/icon.png",
    'PROFILE_BG':  "admin/img/bg.png",
    'LOGIN_LOGO':  "admin/img/icon.png",
    'LOGOUT_BG':  "admin/img/bg.png",
    'SHOW_THEMES': False,
    'TRAY_REVERSE': True,
    'APP_ICONS': {
        'auth': 'group',
        'sites': 'web'
    },
    'MODEL_ICONS': {
        'user': 'person',
        'group': 'people',
        'site': 'web',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

CORS_ORIGIN_ALLOW_ALL = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True