# Generated by Django 2.2.2 on 2019-09-10 17:10

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0006_reservationmotive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecategory_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecategory_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'categoria de calificaciom',
                'verbose_name_plural': 'categorias de calificaciones',
            },
        ),
        migrations.CreateModel(
            name='ScoreCategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('item', basic_app.fields.BasicCharField('Item', choices=[('DEL', 'Delivery'), ('LOC', 'Retiro por el local'), ('RES', 'Reserva')])),
                ('category', basic_app.fields.BasicForeignKey('ScoreCategory', 'Categoria', to='superadmin.ScoreCategory')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecategoryitem_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecategoryitem_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
