# Generated by Django 2.2.2 on 2019-09-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_scorecategory_scorecategoryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecategory',
            options={'verbose_name': 'categoria de calificacion', 'verbose_name_plural': 'categorias de calificaciones'},
        ),
    ]
