# Generated by Django 2.2.2 on 2019-12-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_auto_20190916_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecategory',
            options={'verbose_name': 'categoría de calificacion', 'verbose_name_plural': 'categorías de calificaciones'},
        ),
    ]
