# Generated by Django 2.2.2 on 2019-12-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0065_delete_restaurantlowleveltag'),
        ('superadmin', '0009_auto_20191216_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LowLevelTag',
        ),
    ]
