# Generated by Django 2.1.3 on 2019-06-07 17:12

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('description', basic_app.fields.BasicCharField('Descripción')),
                ('price', basic_app.fields.BasicDecimalField()),
                ('sort_nbr', models.IntegerField(verbose_name='Orden')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
            ],
            options={
                'verbose_name_plural': 'productos',
                'verbose_name': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('address', basic_app.fields.BasicCharField('Dirección', blank=True, null=True)),
                ('is_premium', basic_app.fields.BasicBooleanField('Premium')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Foto principal')),
                ('brand_picture', models.ImageField(blank=True, null=True, upload_to='brand_pictures', verbose_name='Foto de portada')),
                ('delivery', basic_app.fields.BasicBooleanField('Delivery')),
                ('self_service', basic_app.fields.BasicBooleanField('Retiro por el local')),
                ('in_place', basic_app.fields.BasicBooleanField('Comer en el local')),
                ('reservations', basic_app.fields.BasicBooleanField('Acepta reservas')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name_plural': 'restaurantes',
                'verbose_name': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name_plural': 'tags',
                'verbose_name': 'tag',
            },
        ),
        migrations.AddField(
            model_name='restauranttag',
            name='tag',
            field=basic_app.fields.BasicForeignKey('Tag', 'Tag', to='restaurants.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
