# Generated by Django 2.1.3 on 2019-06-10 17:29

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLevelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highleveltag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highleveltag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'tag macro',
                'verbose_name_plural': 'tags macro',
            },
        ),
        migrations.CreateModel(
            name='LowLevelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowleveltag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowleveltag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'tag micro',
                'verbose_name_plural': 'tags micro',
            },
        ),
        migrations.CreateModel(
            name='RestaurantHighLevelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('tag', basic_app.fields.BasicForeignKey('HighLevelTag', 'Tag Macro', to='restaurants.HighLevelTag')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowleveltag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowleveltag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'tag macro',
                'verbose_name_plural': 'tags macro',
            },
        ),
        migrations.CreateModel(
            name='RestaurantLowLevelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('tag', basic_app.fields.BasicForeignKey('LowLevelTag', 'Tag Micro', to='restaurants.LowLevelTag')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowleveltag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowleveltag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'tag macro',
                'verbose_name_plural': 'tags macro',
            },
        ),
        migrations.RemoveField(
            model_name='restauranttag',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restauranttag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='update_user',
        ),
        migrations.DeleteModel(
            name='RestaurantTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
