# Generated by Django 2.1.3 on 2019-06-10 17:41

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190610_1729'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highleveltag',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='highleveltag',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='lowleveltag',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='lowleveltag',
            name='update_user',
        ),
        migrations.AlterField(
            model_name='restauranthighleveltag',
            name='tag',
            field=basic_app.fields.BasicForeignKey('superadmin.HighLevelTag', 'Tag Macro', to='superadmin.HighLevelTag'),
        ),
        migrations.AlterField(
            model_name='restaurantlowleveltag',
            name='tag',
            field=basic_app.fields.BasicForeignKey('superadmin.LowLevelTag', 'Tag Micro', to='superadmin.LowLevelTag'),
        ),
        migrations.DeleteModel(
            name='HighLevelTag',
        ),
        migrations.DeleteModel(
            name='LowLevelTag',
        ),
    ]
