# Generated by Django 2.1.3 on 2019-06-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190612_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranthighleveltag',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauranthighleveltag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AlterField(
            model_name='restauranthighleveltag',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauranthighleveltag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='restaurantlowleveltag',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantlowleveltag_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AlterField(
            model_name='restaurantlowleveltag',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantlowleveltag_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
