# Generated by Django 2.1.3 on 2019-06-13 17:56

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_auto_20190612_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('description', basic_app.fields.BasicCharField('Descripción')),
                ('price', basic_app.fields.BasicDecimalField()),
                ('menu_date', models.DateField(verbose_name='Fecha')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name_plural': 'menues',
                'verbose_name': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('menu', basic_app.fields.BasicForeignKey('Menu', 'Menu', to='restaurants.Menu')),
                ('product', basic_app.fields.BasicForeignKey('Product', 'Producto', to='restaurants.Product')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name_plural': 'productos',
                'verbose_name': 'producto',
            },
        ),
        migrations.AlterField(
            model_name='restaurantlowleveltag',
            name='tag',
            field=basic_app.fields.BasicForeignKey('superadmin.LowLevelTag', 'Tag Micro', to='superadmin.LowLevelTag'),
        ),
    ]
