# Generated by Django 2.1.3 on 2019-06-14 23:43

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_auto_20190613_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fixed_day', basic_app.fields.BasicCharField('Día', choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuday_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='fixed',
            field=basic_app.fields.BasicBooleanField('Fijar día'),
        ),
        migrations.AlterField(
            model_name='menuproduct',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuproduct_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AlterField(
            model_name='menuproduct',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuproduct_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='menuday',
            name='menu',
            field=basic_app.fields.BasicForeignKey('Menu', 'Menu', to='restaurants.Menu'),
        ),
        migrations.AddField(
            model_name='menuday',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuday_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
