# Generated by Django 2.1.3 on 2019-06-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20190614_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuday',
            options={'verbose_name': 'día', 'verbose_name_plural': 'días'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_diners',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Máximo de comenzales'),
        ),
    ]
