# Generated by Django 2.1.3 on 2019-06-18 19:41

import basic_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantattentionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='menuday',
            name='fixed_day',
            field=basic_app.fields.BasicCharField('Día', choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='restaurantattentionschedule',
            name='day',
            field=basic_app.fields.BasicCharField('Día', choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday'), ('-1', 'Feriado')]),
        ),
    ]
