# Generated by Django 2.1.3 on 2019-06-21 15:45

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20190618_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=basic_app.fields.BasicForeignKey('ProductCategory', 'Categoria', default=1, to='ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=basic_app.fields.BasicForeignKey('ProductSubcategory', 'Subcategoria', default=1, to='ProductSubcategory'),
            preserve_default=False,
        ),
    ]
