# Generated by Django 2.2.2 on 2019-06-24 18:34

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0012_restaurant_influence_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantservice_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('service', basic_app.fields.BasicForeignKey('superadmin.Service', 'Servicio', to='superadmin.Service')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantservice_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name_plural': 'servicios',
                'verbose_name': 'servicio',
            },
        ),
    ]
