# Generated by Django 2.2.2 on 2019-06-24 18:22

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_influence_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='influence_range',
            field=basic_app.fields.BasicCharField('Zona de influencia', blank=True, choices=[('Alberti', (('Alberti', 'Alberti'), ('Coronel Seguí', 'Coronel Seguí'), ('Mechita', 'Mechita'), ('Pla', 'Pla'), ('Villa Grisolía', 'Villa Grisolía'), ('Villa María', 'Villa María'), ('Villa Ortiz', 'Villa Ortiz'))), ('Almirante Brown', (('Almirante Brown', 'Almirante Brown'),)), ('Avellaneda', (('Avellaneda', 'Avellaneda'),))], null=True),
        ),
    ]
