# Generated by Django 2.2.2 on 2019-06-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20190624_1822'),
        ('restaurants', '0012_restaurantservice'),
    ]

    operations = [
    ]
