# Generated by Django 2.2.2 on 2019-06-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_merge_20190625_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'subcategory__name', 'sort_nbr'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
