# Generated by Django 2.2.2 on 2019-06-26 15:25

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0003_holiday'),
        ('restaurants', '0015_auto_20190626_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantWorkableHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantworkableholiday_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('holiday', basic_app.fields.BasicForeignKey('superadmin.Holiday', 'Feriado', to='superadmin.Holiday')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantworkableholiday_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
