# Generated by Django 2.2.2 on 2019-06-26 20:07

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_restaurantworkableholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantworkableholiday',
            options={'verbose_name': 'feriado laborable', 'verbose_name_plural': 'feriados laborables'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accept_orders',
            field=basic_app.fields.BasicBooleanField('Ordenes por la App'),
        ),
    ]
