# Generated by Django 2.2.2 on 2019-06-26 20:46

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_auto_20190626_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=basic_app.fields.BasicCharField('Descripción', blank=True, null=True),
        ),
    ]
