# Generated by Django 2.2.2 on 2019-06-28 03:00

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_auto_20190626_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=basic_app.fields.BasicCharField('Descripción', blank=True, null=True),
        ),
    ]
