# Generated by Django 2.2.2 on 2019-06-28 03:05

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0019_auto_20190628_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='brand_picture',
        ),
        migrations.CreateModel(
            name='RestaurantBrandPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('brand_picture', models.ImageField(blank=True, null=True, upload_to='brand_pictures', verbose_name='Foto de portada')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantbrandpicture_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantbrandpicture_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'foto de portada',
                'verbose_name_plural': 'fotos de portada',
            },
        ),
    ]
