# Generated by Django 2.2.2 on 2019-06-28 03:23

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_auto_20190628_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dessert',
            field=basic_app.fields.BasicCharField('Postre', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='main_dish',
            field=basic_app.fields.BasicCharField('Plato principal', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='snack',
            field=basic_app.fields.BasicCharField('Entrada', blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MenuProduct',
        ),
    ]
