# Generated by Django 2.2.2 on 2019-06-28 15:20

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0022_auto_20190628_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_date',
        ),
        migrations.CreateModel(
            name='MenuDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fixed_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menudate_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('menu', basic_app.fields.BasicForeignKey('Menu', 'Menu', to='restaurants.Menu')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menudate_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'día fijo',
                'verbose_name_plural': 'días fijos',
            },
        ),
    ]
