# Generated by Django 2.2.2 on 2019-06-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_auto_20190628_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='fixed',
        ),
    ]
