# Generated by Django 2.2.2 on 2019-06-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_auto_20190628_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'categoria de menu', 'verbose_name_plural': 'categorias de menus'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'categoria de producto', 'verbose_name_plural': 'categorias de productos'},
        ),
    ]
