# Generated by Django 2.2.2 on 2019-06-28 17:19

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0004_paymentmethod'),
        ('restaurants', '0025_auto_20190628_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantpaymentmethod_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('payment_method', basic_app.fields.BasicForeignKey('superadmin.PaymentMethod', 'Método de pago', to='superadmin.PaymentMethod')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantpaymentmethod_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
            },
        ),
    ]
