# Generated by Django 2.2.2 on 2019-07-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_createusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'sub categoria de productos', 'verbose_name_plural': 'sub categorias de productos'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='influence_range',
        ),
    ]
