# Generated by Django 2.2.2 on 2019-07-08 20:09

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_location'),
        ('restaurants', '0028_auto_20190708_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='influence_range',
            field=basic_app.fields.BasicForeignKey('superadmin.Location', 'Zona de influencia', blank=True, null=True, to='superadmin.Location'),
        ),
    ]
