# Generated by Django 2.2.2 on 2019-07-23 19:42

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0029_restaurant_influence_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('address', basic_app.fields.BasicCharField('Dirección')),
                ('phone_nbr', basic_app.fields.BasicCharField('Teléfono')),
                ('expected_payment', basic_app.fields.BasicDecimalField(blank=True, null=True)),
                ('comments', basic_app.fields.BasicCharField('Comentarios', blank=True, null=True)),
                ('price', basic_app.fields.BasicDecimalField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('order', basic_app.fields.BasicForeignKey('Order', 'Pedido', to='restaurants.Order')),
                ('product', basic_app.fields.BasicForeignKey('Product', 'Producto', to='restaurants.Product')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
