# Generated by Django 2.2.2 on 2019-08-05 16:10

import basic_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0030_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=basic_app.fields.BasicBooleanField('Entregado'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
