# Generated by Django 2.2.2 on 2019-08-06 15:03

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0030_order_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermenu_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('menu', basic_app.fields.BasicForeignKey('Menu', 'Menu', to='restaurants.Menu')),
                ('order', basic_app.fields.BasicForeignKey('Order', 'Pedido', to='restaurants.Order')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermenu_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
