# Generated by Django 2.2.2 on 2019-08-06 15:11

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_auto_20190805_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=basic_app.fields.BasicCharField('Descripcion', blank=True, null=True),
        ),
    ]
