# Generated by Django 2.2.2 on 2019-08-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_ordermenu'),
        ('restaurants', '0031_auto_20190805_1610'),
    ]

    operations = [
    ]
