# Generated by Django 2.2.2 on 2019-08-07 18:20

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0032_restaurant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriterestaurant_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriterestaurant_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'restaurante favorito',
                'verbose_name_plural': 'restaurantes favoritos',
            },
        ),
    ]
