# Generated by Django 2.2.2 on 2019-08-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_restaurant_description'),
        ('restaurants', '0032_merge_20190806_1221'),
    ]

    operations = [
    ]
