# Generated by Django 2.2.2 on 2019-08-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_merge_20190809_1318'),
        ('restaurants', '0033_favoriterestaurant'),
    ]

    operations = [
    ]
