# Generated by Django 2.2.2 on 2019-08-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_restaurantdiscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='_price',
        ),
    ]
