# Generated by Django 2.2.2 on 2019-08-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0039_reservation'),
        ('restaurants', '0039_auto_20190820_1543'),
    ]

    operations = [
    ]
