# Generated by Django 2.2.2 on 2019-09-02 17:10

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0040_merge_20190826_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='finished',
            field=basic_app.fields.BasicBooleanField('Reserva Finalizada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=basic_app.fields.BasicCharField('Tipo', choices=[('DEL', 'Delivery'), ('LOC', 'Retiro por el local')]),
        ),
    ]
