# Generated by Django 2.2.2 on 2019-09-06 17:50

import basic_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0041_auto_20190902_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantdiscount',
            options={'verbose_name': 'descuento', 'verbose_name_plural': 'descuentos'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_hour',
            field=models.TimeField(null=True, verbose_name='Horario de Orden'),
        ),
        migrations.AlterField(
            model_name='restaurantdiscount',
            name='applicable_to',
            field=basic_app.fields.BasicCharField('Aplicable a', choices=[('MN', 'Menus'), ('PR', 'Productos')]),
        ),
    ]
