# Generated by Django 2.2.2 on 2019-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0042_auto_20190906_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_hour',
            field=models.TimeField(null=True, verbose_name='Horario de Pedido'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
