# Generated by Django 2.2.2 on 2019-09-16 13:54

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0008_auto_20190916_1054'),
        ('restaurants', '0043_auto_20190910_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('score', models.PositiveSmallIntegerField(verbose_name='puntaje')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderqualification_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('order', basic_app.fields.BasicForeignKey('Order', 'Pedido', to='restaurants.Order')),
                ('score_category', basic_app.fields.BasicForeignKey('superadmin.ScoreCategory', 'Categoria', to='superadmin.ScoreCategory')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderqualification_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
