# Generated by Django 2.2.2 on 2019-10-08 19:20

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0047_auto_20191008_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='restaurant',
            field=basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', default=1, to='Restaurant'),
            preserve_default=False,
        ),
    ]
