# Generated by Django 2.2.2 on 2019-10-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0048_qualification_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='score',
            field=models.FloatField(verbose_name='puntaje'),
        ),
    ]
