# Generated by Django 2.2.2 on 2019-10-11 14:58

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0049_auto_20191009_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='main_dish',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snack',
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('value', basic_app.fields.BasicCharField('Descripcion')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('menu', basic_app.fields.BasicForeignKey('Menu', 'Menu', to='restaurants.Menu')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
