# Generated by Django 2.2.2 on 2019-10-17 19:30

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0050_auto_20191011_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='motive',
            field=basic_app.fields.BasicCharField('Motivo de reserva', blank=True, null=True),
        ),
    ]
