# Generated by Django 2.2.2 on 2019-10-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0051_reservation_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='renewal_time',
            field=models.TimeField(default='20:00', verbose_name='Tiempo de renovacion de mesas'),
        ),
    ]
