# Generated by Django 2.2.2 on 2019-10-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0052_restaurant_renewal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='finished',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='renewal_time',
            field=models.TimeField(default='01:00', verbose_name='Tiempo de renovacion de mesas'),
        ),
    ]
