# Generated by Django 2.2.2 on 2019-10-29 19:04

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0053_auto_20191021_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationproduct_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('product', basic_app.fields.BasicForeignKey('Product', 'Producto', to='restaurants.Product')),
                ('reservation', basic_app.fields.BasicForeignKey('Reservation', 'Reserva', to='restaurants.Reservation')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationproduct_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationmenu_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('menu', basic_app.fields.BasicForeignKey('Menu', 'Menu', to='restaurants.Menu')),
                ('reservation', basic_app.fields.BasicForeignKey('Reservation', 'Reserva', to='restaurants.Reservation')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationmenu_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
