# Generated by Django 2.2.2 on 2019-10-30 17:19

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0054_reservationmenu_reservationproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted',
            field=basic_app.fields.BasicBooleanField('Aceptado'),
        ),
    ]
