# Generated by Django 2.2.2 on 2019-11-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0054_reservationmenu_reservationproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecoveryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.IntegerField(verbose_name='Codigo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrecoverycode_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrecoverycode_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
