# Generated by Django 2.2.2 on 2019-12-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0055_order_accepted'),
        ('restaurants', '0055_userrecoverycode'),
    ]

    operations = [
    ]
