# Generated by Django 2.2.2 on 2019-12-09 13:51

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0056_merge_20191209_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID MP'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_time',
            field=models.IntegerField(choices=[(0, '0'), (15, '15'), (30, '30')], default=0, verbose_name='Tiempo de Espera (mins)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='access_token',
            field=basic_app.fields.BasicCharField('access token', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='public_key',
            field=basic_app.fields.BasicCharField('public key', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdiscount',
            name='day_fixed',
            field=basic_app.fields.BasicCharField('Día de descuento fijo', blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], null=True),
        ),
        migrations.CreateModel(
            name='ProductCategoryAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', basic_app.fields.BasicCharField('Nombre')),
                ('price', basic_app.fields.BasicDecimalField()),
                ('category', basic_app.fields.BasicForeignKey('ProductCategory', 'Categoria', to='restaurants.ProductCategory')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategoryadditional_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategoryadditional_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(restaurants.models.Discountable, models.Model),
        ),
    ]
