# Generated by Django 2.2.2 on 2019-12-11 19:59

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0058_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='additional',
            field=basic_app.fields.BasicForeignKey('ProductCategoryAdditional', 'Adicional', null=True, to='restaurants.ProductCategoryAdditional'),
        ),
    ]
