# Generated by Django 2.2.2 on 2019-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0059_orderproduct_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='access_token',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='access token'),
        ),
    ]
