# Generated by Django 2.2.2 on 2019-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0061_auto_20191215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_hour',
            field=models.TimeField(null=True, verbose_name='Horario de Pedido'),
        ),
    ]
