# Generated by Django 2.2.2 on 2019-12-16 20:49

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0062_auto_20191215_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menú', 'verbose_name_plural': 'menús'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'categoría de menú', 'verbose_name_plural': 'categorías de menús'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'categoría de producto', 'verbose_name_plural': 'categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategoryadditional',
            options={'verbose_name': 'adicional', 'verbose_name_plural': 'adicionales'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'sub categoría de productos', 'verbose_name_plural': 'sub categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'sub menú', 'verbose_name_plural': 'sub menús'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=basic_app.fields.BasicForeignKey('MenuCategory', 'Categoría', to='restaurants.MenuCategory'),
        ),
        migrations.AlterField(
            model_name='menudate',
            name='menu',
            field=basic_app.fields.BasicForeignKey('Menu', 'Menú', to='restaurants.Menu'),
        ),
        migrations.AlterField(
            model_name='menuday',
            name='menu',
            field=basic_app.fields.BasicForeignKey('Menu', 'Menú', to='restaurants.Menu'),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='menu',
            field=basic_app.fields.BasicForeignKey('Menu', 'Menú', to='restaurants.Menu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=basic_app.fields.BasicForeignKey('ProductCategory', 'Categoría', to='restaurants.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=basic_app.fields.BasicForeignKey('ProductSubcategory', 'Subcategoría', to='restaurants.ProductSubcategory'),
        ),
        migrations.AlterField(
            model_name='productcategoryadditional',
            name='category',
            field=basic_app.fields.BasicForeignKey('ProductCategory', 'Categoría', to='restaurants.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=basic_app.fields.BasicForeignKey('ProductCategory', 'Categoría', to='restaurants.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='score_category',
            field=basic_app.fields.BasicForeignKey('superadmin.ScoreCategory', 'Categoría', to='superadmin.ScoreCategory'),
        ),
        migrations.AlterField(
            model_name='reservationmenu',
            name='menu',
            field=basic_app.fields.BasicForeignKey('Menu', 'Menú', to='restaurants.Menu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=basic_app.fields.BasicForeignKey('Menu', 'Menú', to='restaurants.Menu'),
        ),
    ]
