# Generated by Django 2.2.2 on 2019-12-17 13:36

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0063_auto_20191216_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=basic_app.fields.BasicForeignKey('ProductSubcategory', 'Subcategoría', blank=True, null=True, to='restaurants.ProductSubcategory'),
        ),
    ]
