# Generated by Django 2.2.2 on 2019-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0065_delete_restaurantlowleveltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mp_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID MP'),
        ),
    ]
