# Generated by Django 2.2.2 on 2019-12-19 14:10

import basic_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0065_delete_restaurantlowleveltag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurante', 'verbose_name_plural': 'restaurantes'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='self_service',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='self_seervice',
            field=basic_app.fields.BasicBooleanField('Retiro por el local'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='diners',
            field=models.PositiveSmallIntegerField(verbose_name='Cantidad de comensales'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='max_diners',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Máximo de comensales'),
        ),
    ]
