# Generated by Django 2.2.2 on 2019-12-19 14:10

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0066_auto_20191219_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='self_seervice',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='self_service',
            field=basic_app.fields.BasicBooleanField('Retiro por el local'),
        ),
    ]
