# Generated by Django 2.2.2 on 2019-12-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0066_auto_20191219_1822'),
        ('restaurants', '0068_auto_20191219_1130'),
    ]

    operations = [
    ]
