# Generated by Django 2.2.2 on 2019-12-20 14:35

import basic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0069_merge_20191220_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermenu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='reservationmenu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='reservationproduct',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='reservationproduct',
            name='additional',
            field=basic_app.fields.BasicForeignKey('ProductCategoryAdditional', 'Adicional', null=True, to='restaurants.ProductCategoryAdditional'),
        ),
    ]
