# Generated by Django 2.2.2 on 2019-12-27 16:08

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_delete_lowleveltag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0070_auto_20191220_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('location', basic_app.fields.BasicForeignKey('superadmin.Location', 'Location', to='superadmin.Location')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
