# Generated by Django 2.2.2 on 2019-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0071_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mp_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID MP'),
        ),
    ]
