# Generated by Django 2.2.2 on 2019-12-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0071_restaurantadministrator'),
        ('restaurants', '0072_reservation_mp_id'),
    ]

    operations = [
    ]
