# Generated by Django 2.2.2 on 2019-12-30 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0073_merge_20191230_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantadministrator',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantadministrator',
            unique_together={('admin', 'restaurant')},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
