# Generated by Django 2.2.2 on 2020-01-09 15:11

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0075_auto_20191230_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('promotion', models.TextField(blank=True, null=True, verbose_name='Promocion de restaurante')),
                ('promotion_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('day_fixed', basic_app.fields.BasicCharField('Día de promocion fijo', blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], null=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantpromotion_create_user', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('restaurant', basic_app.fields.BasicForeignKey('Restaurant', 'Restaurant', to='restaurants.Restaurant')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantpromotion_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name_plural': 'promociones',
                'verbose_name': 'promocion',
            },
        ),
    ]
