# Generated by Django 2.2.2 on 2020-01-28 20:05

import basic_app.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0076_restaurantpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario cancelación'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelled',
            field=basic_app.fields.BasicBooleanField('Cancelada'),
        ),
        migrations.AlterField(
            model_name='restaurantpromotion',
            name='promotion',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Promocion de restaurante'),
        ),
    ]
