# Generated by Django 2.2.2 on 2020-02-03 16:01

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def forwards_func(apps, schema_editor):
    group = Group.objects.get(name="Administrador del restaurant")
    group.permissions.add(*Permission.objects.filter(codename__in= ['view_restaurantpromotion',
                                                                    'delete_restaurantpromotion',
                                                                    'change_restaurantpromotion',
                                                                    'add_restaurantpromotion',
                                                                    ] ))
    group.save()

def reverse_func(apps, schema_editor):
    group = Group.objects.get(name = "Administrador del restaurant")
    group.permissions.remove(*Permission.objects.filter(codename__in= ['view_restaurantpromotion',
                                                                    'delete_restaurantpromotion',
                                                                    'change_restaurantpromotion',
                                                                    'add_restaurantpromotion',
                                                                    ] ))

class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0076_restaurantpromotion'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]

