# Generated by Django 2.2.2 on 2020-02-03 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0077_auto_20200128_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_cancelled_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario cancelación'),
        ),
    ]
