# Generated by Django 2.2.2 on 2020-02-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0077_permissions_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpromotion',
            name='promotion',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Promocion de restaurante'),
        ),
    ]
