# Generated by Django 2.2.2 on 2020-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0078_auto_20200203_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_nbr'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_nbr'], 'verbose_name': 'categoría de producto', 'verbose_name_plural': 'categorías de productos'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_nbr',
            field=models.IntegerField(default=0, verbose_name='Orden'),
            preserve_default=False,
        ),
    ]
