# Generated by Django 2.2.2 on 2020-02-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0078_reservation_cancelled_user'),
        ('restaurants', '0079_auto_20200209_1545'),
    ]

    operations = [
    ]
